import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const targets = await fetch('http://127.0.0.1:9322/json').then(r => r.json());
const target = targets.find(t => t.type === 'page');
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
let id = 0; const pending = new Map(); const errors = [];
ws.addEventListener('message', event => { const msg = JSON.parse(event.data); if (msg.id) { const p = pending.get(msg.id); pending.delete(msg.id); msg.error ? p.reject(msg.error) : p.resolve(msg.result); } if (msg.method === 'Runtime.exceptionThrown') errors.push(msg.params.exceptionDetails.text); });
const send = (method, params = {}) => new Promise((resolve, reject) => { const n = ++id; pending.set(n, { resolve, reject }); ws.send(JSON.stringify({ id: n, method, params })); });
const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
const wait = async expression => { for (let i = 0; i < 200; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error('Timed out: ' + expression); };
await send('Runtime.enable'); await send('Page.enable');
const expected=JSON.parse(await (await import('node:fs/promises')).readFile(new URL('../docs/example-match.json',import.meta.url),'utf8'));
const base=process.env.GAME_URL||'http://localhost:3000';
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:base});
await wait("document.querySelectorAll('.agent-tab').length>0");
await evaluate("localStorage.removeItem('last-seat-replay-v1');localStorage.removeItem('last-seat-favorites');window.frameTimes=[];let last=performance.now();requestAnimationFrame(function frame(t){window.frameTimes.push(t-last);last=t;if(window.frameTimes.length<180)requestAnimationFrame(frame)});");
await send('Page.reload');
await wait("document.querySelectorAll('.agent-tab').length===4");
await evaluate("document.getElementById('speed').value='4';document.getElementById('speed').dispatchEvent(new Event('change'));document.getElementById('step').click()");
await wait("document.getElementById('turn').textContent==='TURN 01'&&!document.getElementById('step').disabled");
assert.equal(await evaluate("document.getElementById('alive').textContent"),'4 / 4 AT THE TABLE');
await evaluate("document.getElementById('play').click()");
await new Promise(r=>setTimeout(r,200));
await evaluate("document.getElementById('play').click()");
const frozen=await evaluate("({turn:document.getElementById('turn').textContent,feed:document.getElementById('ticker').textContent,credits:document.getElementById('inspect-content').textContent})");
await new Promise(r=>setTimeout(r,700));
assert.deepEqual(await evaluate("({turn:document.getElementById('turn').textContent,feed:document.getElementById('ticker').textContent,credits:document.getElementById('inspect-content').textContent})"),frozen);
await evaluate("document.getElementById('play').click()");
await wait("Number(document.getElementById('turn').textContent.slice(5))>=8");
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-live.png'),Buffer.from(r.data,'base64')));
// Complete the live match.
for(let i=0;i<700;i++){if(await evaluate("!document.getElementById('comparison').hidden"))break;await new Promise(r=>setTimeout(r,100));}
assert.equal(await evaluate("document.getElementById('turn').textContent"),`TURN ${String(expected.final_state.turn).padStart(2,'0')}`);
assert.equal(await evaluate("document.getElementById('alive').textContent"),expected.winner?`${expected.config.agents.find(a=>a.id===expected.winner).name.toUpperCase()} SURVIVES`:'NO SOLE SURVIVOR');
assert.equal(await evaluate("document.querySelectorAll('#comparison tbody tr').length"),4);
await wait("document.getElementById('play').textContent==='▶ Watch again'");
assert.ok(await evaluate("document.querySelectorAll('.moment').length")>=3);
await evaluate("document.querySelector('[data-agent=agent-2]').click();document.getElementById('favorite').click()");
assert.equal(await evaluate("document.getElementById('favorite').textContent"),'★ Following');
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-final.png'),Buffer.from(r.data,'base64')));
await evaluate("window.stepRequests=0;window.originalFetch=window.fetch;window.fetch=(...a)=>{if(String(a[0]).endsWith('/step'))window.stepRequests++;return window.originalFetch(...a)};document.getElementById('replay').click()");
assert.equal(await evaluate("document.getElementById('turn').textContent"),'TURN 00');
await evaluate("document.getElementById('step').click()");
await wait("document.getElementById('turn').textContent==='TURN 01'&&!document.getElementById('step').disabled");
assert.equal(await evaluate('window.stepRequests'),0);
await evaluate("document.getElementById('scrub').value='11';document.getElementById('scrub').dispatchEvent(new Event('input'))");
assert.equal(await evaluate("document.getElementById('turn').textContent"),'TURN 11');
// Shared prefixes must verify without allocating another live session.
const shared=await evaluate("(async()=>{const replay=JSON.parse(localStorage.getItem('last-seat-replay-v1'));const r=await fetch('/api/replays/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({replay})});return r.json()})()");
assert.match(shared.match_id,/^seat-[a-f0-9]{64}$/);
await send('Page.navigate',{url:base+'/?match='+shared.match_id+'&turn=11'});
await wait("document.getElementById('turn').textContent==='TURN 11'");
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-preview.png'),Buffer.from(r.data,'base64')));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
assert.equal(await evaluate('document.documentElement.scrollWidth<=390'),true);
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-mobile.png'),Buffer.from(r.data,'base64')));
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});
await evaluate("document.getElementById('new').click();document.getElementById('population').value='2';document.getElementById('seed').value='9';document.getElementById('preset').click()");
await wait("JSON.parse(document.getElementById('config-json').value).agents.length===2");
await evaluate("document.getElementById('config-form').requestSubmit()");
await wait("document.querySelectorAll('.agent-tab').length===2&&document.getElementById('turn').textContent==='TURN 00'");
await evaluate("document.getElementById('restart').click()");
await wait("document.getElementById('notice').textContent.includes('Seed 9')");
await evaluate("document.getElementById('new').click();document.getElementById('population').value='20';document.getElementById('preset').click()");
await wait("JSON.parse(document.getElementById('config-json').value).agents.length===20");
await evaluate("document.getElementById('config-form').requestSubmit()");
await wait("document.querySelectorAll('.agent-tab').length===20");
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-twenty.png'),Buffer.from(r.data,'base64')));
for(const width of [360,390,430]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate(`document.documentElement.scrollWidth<=${width}`),true);}
await evaluate("document.getElementById('speed').value='4';document.getElementById('speed').dispatchEvent(new Event('change'));document.getElementById('play').click()");
await new Promise(r=>setTimeout(r,1500));
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});assert.equal(await evaluate("matchMedia('(prefers-reduced-motion: reduce)').matches"),false);
const frames=await evaluate("new Promise(resolve=>{const samples=[];let last=performance.now();requestAnimationFrame(function frame(t){samples.push(t-last);last=t;if(samples.length<120)requestAnimationFrame(frame);else resolve(samples.slice(1));});})");
const sorted=frames.slice().sort((a,b)=>a-b);const performanceReport={scene:'20 agents',samples:frames.length,mean_frame_ms:frames.reduce((a,b)=>a+b,0)/frames.length,p95_frame_ms:sorted[Math.floor(sorted.length*.95)],mode:'live animation',reduced_motion:false};
await writeFile(path.join(os.tmpdir(),'last-seat-performance.json'),JSON.stringify(performanceReport,null,2));console.log(performanceReport);
await evaluate("document.getElementById('play').click()");await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await evaluate("matchMedia('(prefers-reduced-motion: reduce)').matches"),true);
assert.deepEqual(errors,[]);
console.log('PASS: Rust-backed turns, four-agent outcome, animations, pause/resume, 4x, inspect/follow, event-only replay, seek, verified share URL, mobile layout, two-agent remix, restart, no browser errors');
ws.close();
