import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const targets = await fetch('http://127.0.0.1:9322/json').then(r => r.json());
const target = targets.find(t => t.type === 'page');
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
let id = 0; const pending = new Map(); const errors = [];
ws.addEventListener('message', event => { const msg = JSON.parse(event.data); if (msg.id) { const p = pending.get(msg.id); pending.delete(msg.id); msg.error ? p.reject(msg.error) : p.resolve(msg.result); } if (msg.method === 'Runtime.exceptionThrown') errors.push(msg.params.exceptionDetails.text); });
const send = (method, params = {}) => new Promise((resolve, reject) => { const n = ++id; pending.set(n, { resolve, reject }); ws.send(JSON.stringify({ id: n, method, params })); });
const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
const wait = async expression => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error('Timed out: ' + expression); };
await send('Runtime.enable'); await send('Page.enable');
const base=process.env.GAME_URL||'http://localhost:3000';
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:base});
await wait("document.querySelectorAll('.agent-tab').length>0");
await evaluate("localStorage.removeItem('last-seat-replay-v1');localStorage.removeItem('last-seat-favorites')");
await send('Page.reload');
await wait("document.querySelectorAll('.agent-tab').length===4");
await evaluate("document.getElementById('speed').value='4';document.getElementById('speed').dispatchEvent(new Event('change'));document.getElementById('step').click()");
await wait("document.getElementById('turn').textContent==='TURN 01'&&!document.getElementById('step').disabled");
assert.equal(await evaluate("document.getElementById('alive').textContent"),'4 / 4 AT THE TABLE');
await evaluate("document.getElementById('play').click()");
await new Promise(r=>setTimeout(r,200));
await evaluate("document.getElementById('play').click()");
const frozen=await evaluate("({turn:document.getElementById('turn').textContent,feed:document.getElementById('ticker').textContent,credits:document.getElementById('inspect-content').textContent})");
await new Promise(r=>setTimeout(r,700));
assert.deepEqual(await evaluate("({turn:document.getElementById('turn').textContent,feed:document.getElementById('ticker').textContent,credits:document.getElementById('inspect-content').textContent})"),frozen);
await evaluate("document.getElementById('play').click()");
// A complete default match takes roughly 25 seconds at 4x.
for(let i=0;i<450;i++){if(await evaluate("!document.getElementById('comparison').hidden"))break;await new Promise(r=>setTimeout(r,100));}
assert.equal(await evaluate("document.getElementById('turn').textContent"),'TURN 15');
assert.equal(await evaluate("document.getElementById('alive').textContent"),'EMBER SURVIVES');
assert.equal(await evaluate("document.querySelectorAll('#comparison tbody tr').length"),4);
await wait("document.getElementById('play').textContent==='▶ Watch again'");
assert.ok(await evaluate("document.querySelectorAll('.moment').length")>=3);
await evaluate("document.querySelector('[data-agent=agent-2]').click();document.getElementById('favorite').click()");
assert.equal(await evaluate("document.getElementById('favorite').textContent"),'★ Following');
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-final.png'),Buffer.from(r.data,'base64')));
await evaluate("window.stepRequests=0;window.originalFetch=window.fetch;window.fetch=(...a)=>{if(String(a[0]).endsWith('/step'))window.stepRequests++;return window.originalFetch(...a)};document.getElementById('replay').click()");
assert.equal(await evaluate("document.getElementById('turn').textContent"),'TURN 00');
await evaluate("document.getElementById('step').click()");
await wait("document.getElementById('turn').textContent==='TURN 01'&&!document.getElementById('step').disabled");
assert.equal(await evaluate('window.stepRequests'),0);
await evaluate("document.getElementById('scrub').value='11';document.getElementById('scrub').dispatchEvent(new Event('input'))");
assert.equal(await evaluate("document.getElementById('turn').textContent"),'TURN 11');
// Shared prefixes must verify without allocating another live session.
const shared=await evaluate("(async()=>{const replay=JSON.parse(localStorage.getItem('last-seat-replay-v1'));const r=await fetch('/api/replays/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({replay})});return r.json()})()");
assert.match(shared.match_id,/^seat-[a-f0-9]{64}$/);
await send('Page.navigate',{url:base+'/?match='+shared.match_id+'&turn=11'});
await wait("document.getElementById('turn').textContent==='TURN 11'");
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-preview.png'),Buffer.from(r.data,'base64')));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
assert.equal(await evaluate('document.documentElement.scrollWidth<=390'),true);
await send('Page.captureScreenshot',{format:'png'}).then(r=>writeFile(path.join(os.tmpdir(),'last-seat-mobile.png'),Buffer.from(r.data,'base64')));
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});
await evaluate("document.getElementById('new').click();document.getElementById('population').value='2';document.getElementById('seed').value='9';document.getElementById('preset').click()");
await wait("JSON.parse(document.getElementById('config-json').value).agents.length===2");
await evaluate("document.getElementById('config-form').requestSubmit()");
await wait("document.querySelectorAll('.agent-tab').length===2&&document.getElementById('turn').textContent==='TURN 00'");
await evaluate("document.getElementById('restart').click()");
await wait("document.getElementById('notice').textContent.includes('Seed 9')");
assert.deepEqual(errors,[]);
console.log('PASS: Rust-backed turns, four-agent winner, animations, pause/resume, 4x, inspect/follow, event-only replay, seek, verified share URL, mobile layout, two-agent remix, restart, no browser errors');
ws.close();
