import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const targets = await fetch('http://127.0.0.1:9322/json').then(r => r.json());
const target = targets.find(t => t.type === 'page');
const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
let id = 0; const pending = new Map(); const errors = [];
ws.addEventListener('message', event => { const msg = JSON.parse(event.data); if (msg.id) { const p = pending.get(msg.id); pending.delete(msg.id); msg.error ? p.reject(msg.error) : p.resolve(msg.result); } if (msg.method === 'Runtime.exceptionThrown') errors.push(msg.params.exceptionDetails.text); });
const send = (method, params = {}) => new Promise((resolve, reject) => { const n = ++id; pending.set(n, { resolve, reject }); ws.send(JSON.stringify({ id: n, method, params })); });
const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
const wait = async expression => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error('Timed out: ' + expression); };
await send('Runtime.enable'); await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false });
await send('Page.navigate', { url: 'http://127.0.0.1:3000' });
await wait("document.querySelectorAll('.sprite-token').length > 0");
await evaluate("localStorage.removeItem('agent-arena-v1')");
await send('Page.reload');
await wait("document.querySelectorAll('.sprite-token').length === 20");
assert.equal(await evaluate("document.querySelectorAll('#leaderboard tr').length"), 20);
assert.equal(await evaluate("Array.from(document.images).every(i => i.complete && i.naturalWidth > 0)"), true);
await evaluate("document.getElementById('speed').value='0'; document.getElementById('step').click()");
await wait("document.getElementById('match-count').textContent === '0001'");
await evaluate("document.querySelector('[data-match]').click()");
await wait("document.getElementById('proof').textContent.includes('verified')");
await evaluate("document.getElementById('pause').click()");
assert.equal(await evaluate("document.getElementById('step').disabled"), true);
await evaluate("document.getElementById('pause').click()");
assert.equal(await evaluate("document.getElementById('step').disabled"), false);
await evaluate("document.querySelector('[name=agents]').value='2'; document.querySelector('[name=mode]').value='survival'; document.querySelector('[name=bankroll]').value='0.09'; document.querySelector('[name=seed]').value='9'; document.getElementById('new-run').requestSubmit()");
assert.equal(await evaluate("document.querySelectorAll('.sprite-token').length"), 2);
await evaluate("document.getElementById('run').click()");
await wait("document.getElementById('run-status').textContent === 'COMPLETE'");
assert.equal(await evaluate("document.getElementById('active-count').textContent"), '1 / 2');
assert.deepEqual(errors, []);
await evaluate("document.querySelector('[name=agents]').value='20'; document.querySelector('[name=mode]').value='bounded'; document.querySelector('[name=bankroll]').value='1'; document.querySelector('[name=seed]').value='42'; document.getElementById('new-run').requestSubmit()");
await evaluate("document.getElementById('tournament').click(); document.getElementById('run').click()");
await wait("document.getElementById('tournament-status').textContent.includes('FINISHED')");
assert.equal(await evaluate("document.getElementById('match-count').textContent"), '0006');
await send('Page.reload');
await wait("document.getElementById('notice').textContent.includes('restored')");
assert.equal(await evaluate("document.getElementById('match-count').textContent"), '0006');
await evaluate("document.getElementById('revenue-form').requestSubmit()");
assert.equal(await evaluate("document.getElementById('treasury-total').textContent"), '0.300');
await evaluate("document.getElementById('revenue-form').requestSubmit()");
assert.equal(await evaluate("document.getElementById('treasury-total').textContent"), '0.300');
await evaluate("document.getElementById('allocate').click()");
await send('Page.reload');
await wait("document.getElementById('notice').textContent.includes('restored')");
assert.deepEqual(errors, []);
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
assert.equal(await evaluate('document.documentElement.scrollWidth <= 390'), true);
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false });
await send('Page.captureScreenshot', { format: 'png' }).then(r => writeFile(path.join(os.tmpdir(), 'agent-arena-preview.png'), Buffer.from(r.data, 'base64')));
console.log('PASS: 20 sprites, standings, match, proof, pause, survival, tournament, verified reload, treasury, mobile layout, no browser errors');
ws.close();
